### ISSUE TITLE
index.html hot-reload

### ISSUE THREAD

**Issue by Totati** [manchenkoff/webpack-bootstrap#1]
Hi! I'm new to webpack, and at first I wanted to create my workplace by myself, but failed, so this repo was like water to me. It's just I could not figure out how to add the tea to the water 😶 
I wanted to make the page reload when I edit the index.html too, and I failed again. Could you help with that?

**Comment by manchenkoff** [comment]
Hi) did you mean hot-reload after saving changes?

**Comment by Totati** [comment]
Yes :+1:

**Comment by manchenkoff** [comment]
It seemed like a bug, I've just [fixed it](https://github.com/manchenkoff/webpack-bootstrap/commit/3da99aa525323eae70d7b5238617bc8cd83be960). Now you can try `npm run start` and make changes in `index.html`, the page should automatically refresh on saving

**Comment by manchenkoff** [comment]
fixed
